[package]
name = "langstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "langstd"
crate-type = ["staticlib"]  

[dependencies]
